name: clearing_client
description: "Call clearly"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  logger: ^2.5.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  flutter_contacts: ^1.1.9
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  go_router: ^15.2.0
  firebase_database: ^11.3.7
  relative_time: ^5.0.0
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.7
  flutter_webrtc: ^0.14.1
  google_sign_in: ^7.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  objectbox_generator: any

flutter:

  uses-material-design: true
  assets:
    - assets/images/logo-512.png


