import '../features/contacts/model/contact.dart';

final sampleContacts = [
  Contact(
      displayName: 'Greg Horowitz',
      firstName: 'Greg',
      lastName: 'Horowitz',
      emails: ['greg.horowitz@gmail.com'],
      phoneNumbers: [],
      lastUpdated: DateTime.now(),
  ),
  Contact(
      displayName: 'Kelley Irma',
      firstName: 'Kelley',
      lastName: 'Irma',
      emails: ['kelly.irma@gmail.com'],
      phoneNumbers: [],
      lastUpdated: DateTime.now(),
  ),
  Contact(
      displayName: 'Cedric Rose',
      firstName: 'Cedric',
      lastName: 'Rose',
      emails: ['cedric.rose@gmail.com'],
      phoneNumbers: [],
      lastUpdated: DateTime.now(),
  ),
  Contact(
      displayName: 'Patience Wallace',
      firstName: 'Patience',
      lastName: 'Wallace',
      emails: ['patience1988@gmail.com'],
      phoneNumbers: [],
      lastUpdated: DateTime.now(),
  ),
  Contact(
      displayName: 'Marley Jones',
      firstName: 'Marley',
      lastName: 'Jones',
      emails: ['mjones@gmail.com'],
      phoneNumbers: [],
      lastUpdated: DateTime.now(),
  ),
  Contact(
      displayName: 'Donna Sherman',
      firstName: 'Donna',
      lastName: 'Sherman',
      emails: ['donna.p.sherman@gmail.com'],
      phoneNumbers: [],
      lastUpdated: DateTime.now(),
  ),
  Contact(
      displayName: 'Anya Fernandez',
      firstName: 'Anya',
      lastName: 'Fernandez',
      emails: ['anya.fernandez@gmail.com'],
      phoneNumbers: [],
      lastUpdated: DateTime.now(),
  ),
];